### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by brokoli18** [go-vikunja/app#91] opened 2024-08-17 08:36 UTC
When I set up a task on the mobile app I set a due date and a reminder, however no notification is displayed on the phone. The notificaiton permission has been granted and using the notification test button on the app works, so I wonder what I am doing wrong.

Android version: 14
Nothing OS: 2.6

**Comment by neon2048** [comment] 2024-08-17 18:43
Same problem here (Google Pixel, Android 14 latest release).

I have one task set up to repeat daily and suddenly stopped receiving notifications for it. Test notification works, just not when the actual task reminder is due.

My suspicion is that it has something to do with new battery optimization related permissions in Android. The tasks.org app has recently started requiring new permissions (see version 13.10 changelog - https://github.com/tasks/tasks/blob/main/CHANGELOG.md - "Android 13+ users must grant additional reminder permissions").

I still had an old version of tasks.org installed from F Droid and didn't receive any notifications there either until I updated it and granted the permission. If I remove the permission, I again don't get any notifications so I'm pretty sure that must be the root cause.

**Comment by Benimautner** [comment] 2024-09-13 19:30
Will be fixed in the new version I will release tonight. The reason was that the package we're using changed what they include in their android manifest, so we were missing some attributes. I'd appreciate feedback to rule out the battery optimization this as soon as I release it.

**Comment by darrylgibbs** [comment] 2024-09-14 01:06
I've upgraded to 0.1.7 on a samsung S21FE, Android 14, and i still dont receive notifications.

**Comment by Benimautner** [comment] 2024-09-15 20:00
@darrylgibbs Can you confirm you tried reminders and due date notifications, the "send test notification" button in the settings works, and what your API version is? Thanks!

**Comment by Benimautner** [comment] 2024-09-15 20:08
Also, if you could try to reinstall the app (fully uninstall and reinstall it) that would be great! Sometimes manifest changes fuck stuff up.

**Comment by brokoli18** [comment] 2024-09-15 20:18
@Benimautner In my case notifications are now working after the upgrade

**Comment by Benimautner** [comment] 2024-09-15 20:19
@brokoli18 great to hear, can you confirm android version and API version? Thanks!

**Comment by brokoli18** [comment] 2024-09-15 20:44
Android version is android 14, but I am not sure what you mean by the API version?

**Comment by Benimautner** [comment] 2024-09-15 20:47
When you log into your Vikunja Web client and go to /about (or click on your username on the top right and click "About", what does it say?
<img width="625" alt="image" src="https://github.com/user-attachments/assets/f7a47ad1-be4a-4473-adfc-c27d8a27bccf">

**Comment by brokoli18** [comment] 2024-09-15 20:49
`Version: v0.24.2`

**Comment by Benimautner** [comment] 2024-09-15 20:49
@brokoli18 Thanks!

**Comment by darrylgibbs** [comment] 2024-09-15 21:27
@Benimautner after running multiple (for lack of a better phrase) A-B tests, i can confirm all is well.

I eventually worked out that having the due date rather than just reminder date, (sorry I'm coming from Google Task logic) was a key factor. Also, just setting a task 1 or 2 min in the future for testing purposes would work. Id need at least 5min and then they'd work flawlessly.

**Comment by Benimautner** [comment] 2024-09-15 21:58
@darrylgibbs thanks for letting me know! If you continue to have those glitches (reminders should also work if the task has no due date, obviously), please open a new issue.

**Closed by Benimautner** 2024-09-15 21:58 UTC
Labels: bug
