### ISSUE TITLE
The app does not support Chinese, resulting in Chinese characters being displayed as garbled text.

### ISSUE THREAD

**Issue by liuzj288** [go-vikunja/app#93] opened 2024-09-13 07:22 UTC
![d376250207ce69e2d920ff9f4b3f174d](https://github.com/user-attachments/assets/44080235-86e9-4a44-ae8e-451c228aff99)

**Comment by kolaente** [comment] 2024-09-13 08:11
Duplicate of https://github.com/go-vikunja/app/issues/82

**Closed by kolaente** 2024-09-13 08:11 UTC
