### ISSUE TITLE
Add support for utf8

### ISSUE THREAD

**Issue by giunz** [go-vikunja/app#92] opened 2024-09-01 11:30 UTC
If i write with Greek characters in the web ui and then open the same task from the Android app, the characters are not shown correctly
![Screenshot_2024-09-01-14-30-17-85_98965c6a1d1dd84fe3dc9a5899bc6fc7](https://github.com/user-attachments/assets/d6b16bfc-d986-4169-a5ab-5317c5e90e61)

**Comment by kolaente** [comment] 2024-09-01 17:14
Duplicate of https://github.com/go-vikunja/app/issues/82

**Closed by kolaente** 2024-09-01 17:14 UTC
