### ISSUE TITLE
Saving list overwrites namespace_id with 0

### ISSUE THREAD

**Issue by worldworm** [go-vikunja/app#13] opened 2022-08-23 10:17 UTC
Hello there,
when you edit and save a list in the app, the namespace_id is set to 0. This makes the list disappear in the web frontend and in the app. You need to manually send a post request and reset the namespace back to the original one.
I'm not sure if it's a bug in the app or the api. If it is the api just give me a heads-up and I will open an issue in Gitea 😀 

Tested with app version v0.0.19-alpha

**Comment by k9withabone** [comment] 2022-08-23 11:02
@Benimautner Maybe this is something to do with the switch to HttpClient (6f43c9357d1b5c96c39e7b0ee8f2a8a0038569ed) again?

**Comment by Benimautner** [comment] 2022-08-23 14:37
Can't reproduce this. What API version are you using?

**Comment by worldworm** [comment] 2022-08-24 07:06
I'am using API-Version: v0.19.2
I will try it tonight with the demo instance to rule out my setup.

**Comment by Benimautner** [comment] 2022-08-24 07:17
Even though I don't think this has to do with the switch to HttpClient as @k9withabone suggested, we have switched back. If you don't mind, please give the file attached to [this](https://github.com/go-vikunja/app/issues/15#issuecomment-1224961850) comment a try.

**Comment by worldworm** [comment] 2022-08-25 21:16
The problem also occurs when using the demo instance at https://try.vikunja.io/.
The custom version of @Benimautner also has this problem.

https://user-images.githubusercontent.com/13227454/186770206-c53bfac5-1012-4ab8-96a4-c6d7ffeff302.mp4

**Comment by Benimautner** [comment] 2022-08-26 05:46
I'm using API version v0.18.1 on my prod release. Everything works flawlessly there.

I just updated my dev release to v0.19.2 and am now experiencing the same bug.

@kolaente I read the docs, there seems to be a namespace_id when updating a list. I am guessing this is mandatory now and through the absence of it the list gets saved to 0?
I will include the namespace id and check if it's still happening.

**Comment by Benimautner** [comment] 2022-08-26 15:46
fixed in v0.0.20-alpha
was indeed the missing namespace_id. is this intended behavior @kolaente ?

**Comment by kolaente** [comment] 2022-09-01 12:03
>  is this intended behavior @kolaente ?

@Benimautner Kind of. The frontend always sends the `namespace_id` when upgrading a list but it should not be possible to set it to 0. I'll fix this in the api.

**Closed** 2022-09-27 21:19 UTC

**Comment by kolaente** [comment] 2022-10-01 13:02
Now also fixed in the api.
